version: "3.9"

services:
  nginx-app-proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx-app-proxy
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - ./backend_fastapi/app_self/__STORAGE_VAULT:/storage_vault:ro
    depends_on:
      - next_frontend
      - fastapi_backend
    networks:
      - datanest_net

  postgres:
    build:
      context: ./postgres_db_docker
      dockerfile: Dockerfile
    container_name: datanestDB_postgres
    restart: unless-stopped
    # ports:
    #   - "9003:5432"
    volumes:
      - ./postgres_db_docker/data:/var/lib/postgresql/db_data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: datanestDB
    networks:
      - datanest_net

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    container_name: redistest
    restart: unless-stopped
    # ports:
    #   - "6379:6379"
    # volumes:
      # - ./redis/data:/data
    networks:
      - datanest_net

  fastapi_backend:
    build:
      context: ./backend_fastapi
      dockerfile: Dockerfile
    container_name: fastapi_backend
    restart: unless-stopped
    environment:
      WATCHPACK_POLLING: "true"
      CHOKIDAR_USEPOLLING: "true"
    # ports:
    #   - "9002:9002"
    volumes:
      - ./backend_fastapi/app_self/__STORAGE_VAULT:/app/__STORAGE_VAULT
      - ./backend_fastapi/app_self/:/app

    depends_on:
      - postgres
      - redis
    networks:
      - datanest_net

  next_frontend:
    build:
      context: ./frontend_next
      dockerfile: Dockerfile
    container_name: next_frontend
    restart: unless-stopped
    environment:
      WATCHPACK_POLLING: "true"
      CHOKIDAR_USEPOLLING: "true"
    # ports:
    #   - "9001:9001"
    volumes:
      - ./frontend_next/app_self/app:/app/app
    networks:
      - datanest_net


networks:
  datanest_net:
    driver: bridge
