--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

-- Started on 2025-10-23 17:50:19

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
-- SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

-- DROP DATABASE IF EXISTS "datanestDB";
--
-- TOC entry 4951 (class 1262 OID 16433)
-- Name: datanestDB; Type: DATABASE; Schema: -; Owner: postgres
--

-- CREATE DATABASE "datanestDB" WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'Polish_Poland.1250';


ALTER DATABASE "datanestDB" OWNER TO postgres;

\connect "datanestDB"

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
-- SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 227 (class 1255 OID 33136)
-- Name: update_last_change(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.update_last_change() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.last_change := FLOOR(EXTRACT(EPOCH FROM now()));
    RETURN NEW;
END;
$$;


ALTER FUNCTION public.update_last_change() OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 16454)
-- Name: ITEMSINFO; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."ITEMSINFO" (
    id bigint NOT NULL,
    path text NOT NULL,
    owner text NOT NULL,
    type text NOT NULL,
    url_token text NOT NULL,
    "isFavourite" boolean DEFAULT false NOT NULL,
    last_change bigint DEFAULT floor(EXTRACT(epoch FROM now()))
);


ALTER TABLE public."ITEMSINFO" OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16453)
-- Name: dirs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."ITEMSINFO" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dirs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 24891)
-- Name: passcodes_info; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.passcodes_info (
    id bigint NOT NULL,
    passcode bigint,
    auth_token uuid DEFAULT gen_random_uuid(),
    type text,
    for_user_token text,
    expires_at timestamp with time zone,
    attempts integer DEFAULT 0 NOT NULL
);


ALTER TABLE public.passcodes_info OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 24890)
-- Name: passcodes_info_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.passcodes_info ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.passcodes_info_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 24759)
-- Name: shared_items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.shared_items (
    id bigint NOT NULL,
    path text,
    type text,
    local_token text,
    access_type text,
    overall_access text,
    owner text,
    parent boolean,
    allowed_by text[],
    "FavouriteOf" text[] DEFAULT '{}'::text[],
    last_change bigint DEFAULT floor(EXTRACT(epoch FROM now()))
);


ALTER TABLE public.shared_items OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 24758)
-- Name: shared_item_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.shared_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shared_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 16434)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    email text,
    password text,
    creation_date timestamp with time zone DEFAULT now(),
    "isDev" boolean DEFAULT false,
    user_token uuid DEFAULT gen_random_uuid()
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 16448)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 24708)
-- Name: zipinfo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.zipinfo (
    id bigint NOT NULL,
    zip_token text,
    user_token text,
    crt_date timestamp with time zone DEFAULT now()
);


ALTER TABLE public.zipinfo OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 24707)
-- Name: zipinfo_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.zipinfo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.zipinfo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4939 (class 0 OID 16454)
-- Dependencies: 220
-- Data for Name: ITEMSINFO; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."ITEMSINFO" (id, path, owner, type, url_token, "isFavourite", last_change) FROM stdin;
\.


--
-- TOC entry 4945 (class 0 OID 24891)
-- Dependencies: 226
-- Data for Name: passcodes_info; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.passcodes_info (id, passcode, auth_token, type, for_user_token) FROM stdin;
512	467401	b646dfd4-5cf5-4373-b17e-eac9f01bedd9	register	{"address": "lukas.de1keizer2@gmail.com", "passwd": "Liduka35"}
\.


--
-- TOC entry 4943 (class 0 OID 24759)
-- Dependencies: 224
-- Data for Name: shared_items; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.shared_items (id, path, type, local_token, access_type, overall_access, owner, parent, allowed_by, "FavouriteOf", last_change) FROM stdin;
\.


--
-- TOC entry 4936 (class 0 OID 16434)
-- Dependencies: 217
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, email, password, creation_date, "isDev", user_token) FROM stdin;
71	root@dash.io	$2b$12$.TpofGwqbbOxWBkGl7YzOO4juOOExLwk/E1ALC22Nfh7WxcQUyQR2	2025-10-23 13:27:57.534034+02	t	1d9a858a-0479-4dff-9c36-e11c644f054f
\.


--
-- TOC entry 4941 (class 0 OID 24708)
-- Dependencies: 222
-- Data for Name: zipinfo; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.zipinfo (id, zip_token, user_token, crt_date) FROM stdin;
\.


--
-- TOC entry 4952 (class 0 OID 0)
-- Dependencies: 219
-- Name: dirs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.dirs_id_seq', 59496, true);


--
-- TOC entry 4953 (class 0 OID 0)
-- Dependencies: 225
-- Name: passcodes_info_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.passcodes_info_id_seq', 514, true);


--
-- TOC entry 4954 (class 0 OID 0)
-- Dependencies: 223
-- Name: shared_item_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.shared_item_id_seq', 859, true);


--
-- TOC entry 4955 (class 0 OID 0)
-- Dependencies: 218
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 74, true);


--
-- TOC entry 4956 (class 0 OID 0)
-- Dependencies: 221
-- Name: zipinfo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.zipinfo_id_seq', 393, true);


--
-- TOC entry 4778 (class 2606 OID 16460)
-- Name: ITEMSINFO dirs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ITEMSINFO"
    ADD CONSTRAINT dirs_pkey PRIMARY KEY (id);


--
-- TOC entry 4786 (class 2606 OID 24896)
-- Name: passcodes_info passcodes_info_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.passcodes_info
    ADD CONSTRAINT passcodes_info_pkey PRIMARY KEY (id);


--
-- TOC entry 4784 (class 2606 OID 24765)
-- Name: shared_items shared_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shared_items
    ADD CONSTRAINT shared_items_pkey PRIMARY KEY (id);


--
-- TOC entry 4772 (class 2606 OID 24900)
-- Name: passcodes_info type_check; Type: CHECK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE public.passcodes_info
    ADD CONSTRAINT type_check CHECK ((type = ANY (ARRAY['login'::text, 'register'::text, 'reset_password'::text]))) NOT VALID;


--
-- TOC entry 4774 (class 2606 OID 16452)
-- Name: users unique_email; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT unique_email UNIQUE (email);


--
-- TOC entry 4780 (class 2606 OID 24674)
-- Name: ITEMSINFO unique_stuff; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ITEMSINFO"
    ADD CONSTRAINT unique_stuff UNIQUE (path, url_token, id);


--
-- TOC entry 4776 (class 2606 OID 16440)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 4782 (class 2606 OID 24715)
-- Name: zipinfo zipinfo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.zipinfo
    ADD CONSTRAINT zipinfo_pkey PRIMARY KEY (id);


--
-- TOC entry 4789 (class 2620 OID 33162)
-- Name: ITEMSINFO itemsinfo_last_change_trigger; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER itemsinfo_last_change_trigger BEFORE INSERT OR UPDATE ON public."ITEMSINFO" FOR EACH ROW EXECUTE FUNCTION public.update_last_change();


--
-- TOC entry 4790 (class 2620 OID 33163)
-- Name: shared_items shared_items_last_change_trigger; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER shared_items_last_change_trigger BEFORE INSERT OR UPDATE ON public.shared_items FOR EACH ROW EXECUTE FUNCTION public.update_last_change();


--
-- TOC entry 4788 (class 2606 OID 33153)
-- Name: shared_items belongs_to; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shared_items
    ADD CONSTRAINT belongs_to FOREIGN KEY (owner) REFERENCES public.users(email) ON DELETE CASCADE NOT VALID;


--
-- TOC entry 4787 (class 2606 OID 33189)
-- Name: ITEMSINFO belongs_to; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ITEMSINFO"
    ADD CONSTRAINT belongs_to FOREIGN KEY (owner) REFERENCES public.users(email) NOT VALID;


--
-- Name: user_sessions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE IF NOT EXISTS public.user_sessions (
    id bigint NOT NULL,
    token uuid DEFAULT gen_random_uuid() NOT NULL,
    user_email text NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    expires_at timestamp with time zone NOT NULL
);


ALTER TABLE public.user_sessions OWNER TO postgres;

ALTER TABLE public.user_sessions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.user_sessions
    ADD CONSTRAINT user_sessions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.user_sessions
    ADD CONSTRAINT user_sessions_token_key UNIQUE (token);

CREATE INDEX IF NOT EXISTS user_sessions_token_idx ON public.user_sessions USING btree (token);
CREATE INDEX IF NOT EXISTS user_sessions_user_email_idx ON public.user_sessions USING btree (user_email);

ALTER TABLE public.passcodes_info ADD COLUMN IF NOT EXISTS expires_at timestamp with time zone;
ALTER TABLE public.passcodes_info ADD COLUMN IF NOT EXISTS attempts integer DEFAULT 0;


-- Completed on 2025-10-23 17:50:19

--
-- PostgreSQL database dump complete
--

